---
title: "Day 4 Comp Sesh 4"
format: html
editor: visual
---

## vectors

```{r}
rain <- c(4, 6, 8, 9)

rain_scale <- 5 * rain
```

matrix

```{r}
my_values <- seq(from = 1, to = 10)
```

wrap into a matrix

```{r}
my_matrix <- matrix(my_values, nrow = 2, ncol = 5, byrow = TRUE)
```

```{r}
my_matrix2 <- matrix(data = my_values, nrow = 3, ncol = 4, byrow = TRUE)
```

```{r}
matrix_a <- matrix(data = seq(from = 2, to = 5, length = 10), 
                   nrow = 2, 
                   ncol = 5, 
                   byrow = TRUE)
```

matrix addition/subtraction

```{r}
my_matrix + matrix_a
```

matrix multiplication

```{r}
# can create data directly in the matrix by using c() to create a vector. matrix function wraps it into a matrix
cats <- matrix(data = c(0, 4, 3, 1),
               nrow = 2,
               ncol = 2,
               byrow = TRUE)

dogs <- matrix(data = c(6, 7, 8, 10),
               nrow = 2,
               ncol = 2,
               byrow = TRUE)
```

```{r}
# use the dot product symbol to multiply matrices
cats %*% dogs
```

Leslie matrix example

```{r}
insect_leslie <- matrix(data = c(0, 0, 600, .2, 0, 0, 0, .08, 0),
                        ncol = 3,
                        nrow = 3,
                        byrow = TRUE)

insect_y0 <- c(12000, 700, 500)
```

find population structure for each life stage at t = 1 year

```{r}
insect_y1 <- insect_leslie %*% insect_y0
```

find population structure at t = 2 years

```{r}
insect_y2 <- insect_leslie %*% insect_y1
```
